name: Fetch News Cron Job

on:
  schedule:
    - cron: '11 5 * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install supabase gnews python-dotenv
    
    - name: Run news fetcher
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        GNEWS_LANGUAGE: en
        GNEWS_COUNTRY: NG
        GNEWS_PERIOD: 7d
        GNEWS_MAX_RESULTS: 10
      run: python scripts/fetch_news.py
